package eu.midnightdust.visualoverhaul.compat.phonos.block;

import io.github.foundationgames.phonos.block.PhonosBlocks;
import io.github.foundationgames.phonos.block.RadioJukeboxBlock;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.BlockState;
import net.minecraft.state.StateManager;
import net.minecraft.state.property.BooleanProperty;
import net.minecraft.state.property.IntProperty;

public class RadioJukeboxTop extends Block {
    public static final BooleanProperty PLAYING = RadioJukeboxBlock.PLAYING;
    public static final IntProperty CHANNEL = RadioJukeboxBlock.CHANNEL;

    public RadioJukeboxTop() {
        super(AbstractBlock.Settings.copy(PhonosBlocks.RADIO_JUKEBOX));
        this.setDefaultState(this.stateManager.getDefaultState());
    }

    @Override
    protected void appendProperties(StateManager.Builder<Block, BlockState> builder) {
        builder.add(PLAYING, CHANNEL);
    }
}
